# Generated by Django 5.1.6 on 2025-02-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='expertise',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
